"""
Module for OTIO regression testing
"""
from __future__ import annotations
import opentimelineio._otio
import typing
__all__ = ['bash_retainers1', 'bash_retainers2', 'gil_scoping', 'takeme', 'test_AnyDictionary_destroy', 'test_AnyVector_destroy', 'test_big_uint', 'xyzzy']
def bash_retainers1(arg0: opentimelineio._otio.SerializableCollection) -> int:
    ...
def bash_retainers2(arg0: opentimelineio._otio.SerializableCollection, arg1: typing.Any) -> typing.Any:
    ...
def gil_scoping() -> None:
    ...
def takeme(arg0: opentimelineio._otio.SerializableObject) -> None:
    ...
def test_AnyDictionary_destroy(arg0: opentimelineio._otio.AnyDictionary) -> None:
    ...
def test_AnyVector_destroy(arg0: opentimelineio._otio.AnyVector) -> None:
    ...
def test_big_uint() -> bool:
    ...
def xyzzy(arg0: str) -> None:
    ...
